container:
    image: node:latest
    additional_containers:
      - name: mysql
        image: mysql:latest
        port: 3306
        cpu: 1.0
        memory: 512Mi
        env:
            MYSQL_ROOT_PASSWORD: ""
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
task:
    environment:
        TEST: test
    script: 
    - node --version
    - echo "hello"
    - pwd
    - ls -la
    - cd
    - ls -la
    - mkdir .ssh
    - chmod 700 .ssh
    - cd .ssh
    - ls -la
